// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type RefreshToken struct {
	Jti       string
	UserID    string
	ExpiresAt pgtype.Timestamptz
	Revoked   bool
}

type User struct {
	UserID       string
	Username     string
	Email        string
	PasswordHash string
	Role         string
	CreatedAt    pgtype.Timestamptz
}
