// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertRefreshToken = `-- name: InsertRefreshToken :exec
INSERT INTO refresh_tokens (
    jti,
    user_id,
    expires_at
) VALUES (
    $1, $2, $3
)
`

type InsertRefreshTokenParams struct {
	Jti       string
	UserID    string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, insertRefreshToken, arg.Jti, arg.UserID, arg.ExpiresAt)
	return err
}

const isRefreshTokenValid = `-- name: IsRefreshTokenValid :one
SELECT EXISTS (
    SELECT 1
    FROM refresh_tokens
    WHERE jti = $1
      AND revoked = FALSE
      AND expires_at > NOW()
)
`

func (q *Queries) IsRefreshTokenValid(ctx context.Context, jti string) (bool, error) {
	row := q.db.QueryRow(ctx, isRefreshTokenValid, jti)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const markRefreshTokenRevoked = `-- name: MarkRefreshTokenRevoked :exec
UPDATE refresh_tokens
SET revoked = TRUE
WHERE jti = $1
`

func (q *Queries) MarkRefreshTokenRevoked(ctx context.Context, jti string) error {
	_, err := q.db.Exec(ctx, markRefreshTokenRevoked, jti)
	return err
}

const revokeAllRefreshTokensForUser = `-- name: RevokeAllRefreshTokensForUser :exec
UPDATE refresh_tokens
SET revoked = TRUE
WHERE user_id = $1
`

func (q *Queries) RevokeAllRefreshTokensForUser(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, revokeAllRefreshTokensForUser, userID)
	return err
}
