// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: acl.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAssetACLEntry = `-- name: DeleteAssetACLEntry :exec
DELETE FROM asset_acl WHERE asset_id = $1 AND user_id = $2
`

type DeleteAssetACLEntryParams struct {
	AssetID string
	UserID  string
}

func (q *Queries) DeleteAssetACLEntry(ctx context.Context, arg DeleteAssetACLEntryParams) error {
	_, err := q.db.Exec(ctx, deleteAssetACLEntry, arg.AssetID, arg.UserID)
	return err
}

const getAssetACL = `-- name: GetAssetACL :one
SELECT asset_id, user_id, access_level
FROM asset_acl
WHERE asset_id = $1 AND user_id = $2
`

type GetAssetACLParams struct {
	AssetID string
	UserID  string
}

func (q *Queries) GetAssetACL(ctx context.Context, arg GetAssetACLParams) (AssetAcl, error) {
	row := q.db.QueryRow(ctx, getAssetACL, arg.AssetID, arg.UserID)
	var i AssetAcl
	err := row.Scan(&i.AssetID, &i.UserID, &i.AccessLevel)
	return i, err
}

const getDescendantIDs = `-- name: GetDescendantIDs :many
WITH RECURSIVE descendants AS (
    SELECT b.asset_id FROM assets b WHERE b.parent_id = $1
    UNION ALL
    SELECT a.asset_id FROM assets a
    JOIN descendants d ON a.parent_id = d.asset_id
)
SELECT asset_id FROM descendants
`

func (q *Queries) GetDescendantIDs(ctx context.Context, parentID pgtype.Text) ([]string, error) {
	rows, err := q.db.Query(ctx, getDescendantIDs, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var asset_id string
		if err := rows.Scan(&asset_id); err != nil {
			return nil, err
		}
		items = append(items, asset_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAssetACL = `-- name: UpsertAssetACL :exec
INSERT INTO asset_acl (asset_id, user_id, access_level)
VALUES ($1, $2, $3)
ON CONFLICT (asset_id, user_id) DO UPDATE SET access_level = EXCLUDED.access_level
`

type UpsertAssetACLParams struct {
	AssetID     string
	UserID      string
	AccessLevel string
}

func (q *Queries) UpsertAssetACL(ctx context.Context, arg UpsertAssetACLParams) error {
	_, err := q.db.Exec(ctx, upsertAssetACL, arg.AssetID, arg.UserID, arg.AccessLevel)
	return err
}
