// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAssetsByOwner = `-- name: CountAssetsByOwner :one
SELECT COUNT(*) FROM assets WHERE owner_id = $1
`

func (q *Queries) CountAssetsByOwner(ctx context.Context, ownerID string) (int64, error) {
	row := q.db.QueryRow(ctx, countAssetsByOwner, ownerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAsset = `-- name: CreateAsset :one
INSERT INTO assets (owner_id, parent_id, type, title, content) 
VALUES ($1, $2, $3, $4, $5) 
RETURNING asset_id, owner_id, parent_id, type, title, content, created_at
`

type CreateAssetParams struct {
	OwnerID  string
	ParentID pgtype.Text
	Type     string
	Title    string
	Content  pgtype.Text
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, createAsset,
		arg.OwnerID,
		arg.ParentID,
		arg.Type,
		arg.Title,
		arg.Content,
	)
	var i Asset
	err := row.Scan(
		&i.AssetID,
		&i.OwnerID,
		&i.ParentID,
		&i.Type,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAsset = `-- name: DeleteAsset :exec
DELETE FROM assets WHERE asset_id = $1
`

func (q *Queries) DeleteAsset(ctx context.Context, assetID string) error {
	_, err := q.db.Exec(ctx, deleteAsset, assetID)
	return err
}

const getAssetByID = `-- name: GetAssetByID :one
SELECT asset_id, owner_id, parent_id, type, title, content, created_at FROM assets WHERE asset_id = $1
`

func (q *Queries) GetAssetByID(ctx context.Context, assetID string) (Asset, error) {
	row := q.db.QueryRow(ctx, getAssetByID, assetID)
	var i Asset
	err := row.Scan(
		&i.AssetID,
		&i.OwnerID,
		&i.ParentID,
		&i.Type,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const listAssets = `-- name: ListAssets :many
SELECT asset_id, owner_id, parent_id, type, title, content, created_at
FROM assets 
WHERE owner_id = $1 
ORDER BY created_at DESC 
LIMIT $2 
OFFSET $3
`

type ListAssetsParams struct {
	OwnerID string
	Limit   int32
	Offset  int32
}

func (q *Queries) ListAssets(ctx context.Context, arg ListAssetsParams) ([]Asset, error) {
	rows, err := q.db.Query(ctx, listAssets, arg.OwnerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Asset
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.AssetID,
			&i.OwnerID,
			&i.ParentID,
			&i.Type,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAsset = `-- name: UpdateAsset :one
UPDATE assets
SET title = $2, content = $3
WHERE asset_id = $1
RETURNING asset_id, owner_id, parent_id, type, title, content, created_at
`

type UpdateAssetParams struct {
	AssetID string
	Title   string
	Content pgtype.Text
}

func (q *Queries) UpdateAsset(ctx context.Context, arg UpdateAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, updateAsset, arg.AssetID, arg.Title, arg.Content)
	var i Asset
	err := row.Scan(
		&i.AssetID,
		&i.OwnerID,
		&i.ParentID,
		&i.Type,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}
