// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"
)

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_log(event_type, payload, received_at)
VALUES ($1, $2, NOW())
`

type InsertAuditLogParams struct {
	EventType string
	Payload   []byte
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog, arg.EventType, arg.Payload)
	return err
}
