// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Asset struct {
	AssetID   string
	OwnerID   string
	ParentID  pgtype.Text
	Type      string
	Title     string
	Content   pgtype.Text
	CreatedAt pgtype.Timestamptz
}

type Team struct {
	TeamID    string
	TeamName  string
	CreatedBy string
	UpdatedAt pgtype.Timestamptz
}

type TeamMember struct {
	TeamID string
	UserID string
	Role   string
}

type UsersProjection struct {
	UserID    string
	Username  string
	Email     string
	Role      string
	DeletedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
