// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teams.sql

package db

import (
	"context"
)

const addTeamMember = `-- name: AddTeamMember :exec
INSERT INTO team_members (team_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (team_id, user_id) DO UPDATE
    SET role = EXCLUDED.role
`

type AddTeamMemberParams struct {
	TeamID string
	UserID string
	Role   string
}

func (q *Queries) AddTeamMember(ctx context.Context, arg AddTeamMemberParams) error {
	_, err := q.db.Exec(ctx, addTeamMember, arg.TeamID, arg.UserID, arg.Role)
	return err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (team_id, team_name, created_by)
VALUES (gen_random_uuid()::text, $1, $2)
RETURNING team_id, team_name, created_by, updated_at
`

type CreateTeamParams struct {
	TeamName  string
	CreatedBy string
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam, arg.TeamName, arg.CreatedBy)
	var i Team
	err := row.Scan(
		&i.TeamID,
		&i.TeamName,
		&i.CreatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getMemberRole = `-- name: GetMemberRole :one
SELECT tm.role FROM team_members tm
JOIN users_projection up ON tm.user_id = up.user_id
WHERE tm.team_id = $1 AND tm.user_id = $2 AND up.deleted_at IS NULL
`

type GetMemberRoleParams struct {
	TeamID string
	UserID string
}

func (q *Queries) GetMemberRole(ctx context.Context, arg GetMemberRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getMemberRole, arg.TeamID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getTeamByID = `-- name: GetTeamByID :one
SELECT team_id, team_name, created_by, updated_at FROM teams WHERE team_id = $1
`

func (q *Queries) GetTeamByID(ctx context.Context, teamID string) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByID, teamID)
	var i Team
	err := row.Scan(
		&i.TeamID,
		&i.TeamName,
		&i.CreatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamMembers = `-- name: GetTeamMembers :many
SELECT tm.user_id, tm.role, up.username, up.email 
FROM team_members tm
JOIN users_projection up ON up.user_id = tm.user_id AND up.deleted_at IS NULL
WHERE tm.team_id = $1
ORDER BY tm.role, up.username
`

type GetTeamMembersRow struct {
	UserID   string
	Role     string
	Username string
	Email    string
}

func (q *Queries) GetTeamMembers(ctx context.Context, teamID string) ([]GetTeamMembersRow, error) {
	rows, err := q.db.Query(ctx, getTeamMembers, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTeamMembersRow
	for rows.Next() {
		var i GetTeamMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Role,
			&i.Username,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserProjectionByID = `-- name: GetUserProjectionByID :one
SELECT user_id, username, email, role, deleted_at, updated_at FROM users_projection WHERE user_id = $1
AND deleted_at IS NULL
`

func (q *Queries) GetUserProjectionByID(ctx context.Context, userID string) (UsersProjection, error) {
	row := q.db.QueryRow(ctx, getUserProjectionByID, userID)
	var i UsersProjection
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.Role,
		&i.DeletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isManagerOfMember = `-- name: IsManagerOfMember :one
SELECT EXISTS (
    SELECT 1 FROM team_members tm_manager
    JOIN team_members tm_member ON tm_manager.team_id = tm_member.team_id
    JOIN users_projection up_manager ON up_manager.user_id = tm_manager.user_id
    JOIN users_projection up_member ON up_member.user_id = tm_member.user_id
    WHERE tm_manager.user_id = $1
    AND tm_manager.role = 'manager'
    AND tm_member.user_id = $2
    AND up_manager.deleted_at IS NULL
    AND up_member.deleted_at IS NULL
)
`

type IsManagerOfMemberParams struct {
	ManagerID string
	MemberID  string
}

func (q *Queries) IsManagerOfMember(ctx context.Context, arg IsManagerOfMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isManagerOfMember, arg.ManagerID, arg.MemberID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const removeTeamMember = `-- name: RemoveTeamMember :execrows
DELETE FROM team_members WHERE team_id = $1 AND user_id = $2
`

type RemoveTeamMemberParams struct {
	TeamID string
	UserID string
}

func (q *Queries) RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeTeamMember, arg.TeamID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
