// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users_projection.sql

package db

import (
	"context"
)

const softDeleteUserProjection = `-- name: SoftDeleteUserProjection :exec
UPDATE users_projection
SET deleted_at = NOW()
WHERE user_id = $1
`

func (q *Queries) SoftDeleteUserProjection(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, softDeleteUserProjection, userID)
	return err
}

const upsertUserProjection = `-- name: UpsertUserProjection :exec
INSERT INTO users_projection (user_id, username, email, role, updated_at)
VALUES ($1, $2, $3, $4, NOW())
ON CONFLICT (user_id) DO UPDATE
    SET username = EXCLUDED.username,
        email = EXCLUDED.email,
        role = EXCLUDED.role,
        deleted_at = NULL,
        updated_at = NOW()
`

type UpsertUserProjectionParams struct {
	UserID   string
	Username string
	Email    string
	Role     string
}

func (q *Queries) UpsertUserProjection(ctx context.Context, arg UpsertUserProjectionParams) error {
	_, err := q.db.Exec(ctx, upsertUserProjection,
		arg.UserID,
		arg.Username,
		arg.Email,
		arg.Role,
	)
	return err
}
